#!/bin/bash

# Copyright (C) 2012 GRNET S.A.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

. common.sh

# Read environment according to API version.
ganeti_os_main

# If the device we will import to, is not a real block device,
# we'll first losetup it. This is needed for file disks.
if [ ! -b "$blockdev" ]; then
    original_blockdev="$blockdev"
    blockdev=$($LOSETUP --show -f "$blockdev")
    add_cleanup $LOSETUP -d "$blockdev"
fi

dd of="$blockdev" bs=4M

# Execute cleanups
cleanup
trap - EXIT

exit 0

# vim: set sta sts=4 shiftwidth=4 sw=4 et ai :
