#!/usr/bin/env python

# Copyright (C) 2011-2014 GRNET S.A.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

"""
A tool that connects to the Pithos backend and returns the size and contents
of a pithos object.

Since the backend does not have a "root" account we use the account given in
the URL as the user when connecting to the backend.
"""

from optparse import OptionParser, OptionGroup
from sys import exit, stdout, stderr
from os import environ, umask
from binascii import hexlify, unhexlify
from collections import namedtuple
from pkg_resources import parse_version

try:
    from pithos.backends.modular import ModularBackend
    from pithos.backends.version import __version__ as pithos_backend_version
except ImportError:
    stderr.write("Pithos backend was not found.\n")
    exit(2)

SELECTABLE_BE_VER = "0.15.1"
MB_NO_ARCHIPELAGO_VER = 0
MB_ARCHIPELAGO_VER = 1

note = """
NOTE: You can pass all arguments through environment variables instead of
the command line: Setting the environment variable PITHCAT_XXX to
VALUE is equivalent to passing a '--xxx VALUE' argument.

Using the --db argument directly is dangerous, because it may
expose sensitive information in the output of 'ps'. Consider passing
the DB URI through the environment variable PITHCAT_DB instead.\n"""

try:
    mb_version = ModularBackend._class_version
except AttributeError:
    mb_version = MB_NO_ARCHIPELAGO_VER

OptionParser.format_epilog = lambda self, formattxt: self.epilog
parser = OptionParser(usage='%prog [options] <URL>', epilog=note)
if parse_version(pithos_backend_version) >= parse_version(SELECTABLE_BE_VER) \
        and mb_version == MB_NO_ARCHIPELAGO_VER:
    backend_group = OptionGroup(
        parser, "Backend-specific Options",
        "The backend-specific options depend on the specific "
        "version of Pithos backend (package snf-pithos-backend) installed.\n"
        "(Currently-installed version: Pithos backend '%s')" %
        pithos_backend_version)
    backend_group.add_option('--backend', dest='backend', metavar='BACKEND',
                             help='Pithos backend storage type', default=None)
    backend_group.add_option('--rados-conf', dest='rconf', metavar='RCONF',
                             help='RADOS configuration file to use',
                             default=None)
    backend_group.add_option('--rados-maps', dest='rmaps', metavar='RMAPS',
                             help='RADOS pool which Pithos maps reside',
                             default=None)
    backend_group.add_option('--rados-blocks', dest='rblocks',
                             metavar='RBLOCKS',
                             help='RADOS pool which Pithos blocks reside',
                             default=None)
    backend_group.add_option('--data', dest='data', metavar='DIR',
                             help='path to the directory where data are stored'
                             )
    parser.add_option_group(backend_group)
elif parse_version(pithos_backend_version) < parse_version(SELECTABLE_BE_VER) \
        and mb_version == MB_NO_ARCHIPELAGO_VER:
    parser.add_option('--data', dest='data', metavar='DIR',
                      help='path to the directory where data are stored')
elif mb_version == MB_ARCHIPELAGO_VER:
    parser.add_option('--archipelago-conf', dest='archipconf', metavar='ACONF',
                      help='Archipelago configuration file to use')

parser.add_option('-s', action='store_true', dest='size', default=False,
                  help='print file size and exit')
parser.add_option('--db', dest='db', metavar='URI',
                  help='SQLAlchemy URI of the database [DANGEROUS: Do not use,'
                  'see NOTE below]', default=None)
parser.add_option('--umask', dest='umask', metavar='UMASK', type='int',
                  default=None,
                  help='change the process\' file mode mask to UMASK')

LocationURL = namedtuple('LocationURL', ['account', 'container', 'object'])
HashmapURL = namedtuple('HashmapURL', ['hash', 'size'])


def parse_url(url):
    if url.startswith('pithos://'):
        t = url.split('/', 4)
        assert len(t) == 5, "Invalid URL"
        return LocationURL(*t[2:5])
    elif url.startswith('pithosmap://'):
        t = url.split('/', 3)
        assert len(t) == 4, "Invalid URL"
        return HashmapURL(*t[2:4])
    else:
        raise Exception("Invalid URL")


def print_size(backend, url):
    """Writes object's size to stdout."""
    if type(url) is LocationURL:
        account, container, object = url
        meta = backend.get_object_meta(account, account, container, object,
                                       None)
        print meta['bytes']
    elif type(url) is HashmapURL:
        print url.size
    else:
        raise Exception("Invalid URL")


def print_data(backend, url):
    """Writes object's size to stdout."""

    if type(url) is LocationURL:
        account, container, object = url
        if mb_version == MB_NO_ARCHIPELAGO_VER:
            size, hashmap = backend.get_object_hashmap(account, account,
                                                       container,
                                                       object)
        else:
            _, size, hashmap = backend.get_object_hashmap(account, account,
                                                          container,
                                                          object)
    elif type(url) is HashmapURL:
        size = int(url.size)
        if mb_version == MB_NO_ARCHIPELAGO_VER:
            hashmap = [hexlify(x)
                       for x in backend.store.map_get(unhexlify(url.hash))]
        else:
            hashmap = [x for x in backend.store.map_get(url.hash, size)]
    else:
        raise Exception("Invalid URL")

    for hash in hashmap:
        block = backend.get_block(hash)
        if len(block) > size:
            block = block[:size]
        stdout.write(block)
        size -= len(block)


def main():
    options, args = parser.parse_args()
    if len(args) != 1:
        parser.print_help()
        exit(1)

    if options.umask is not None:
        umask(options.umask)

    url = parse_url(args[0])

    data_path = None

    if parse_version(pithos_backend_version) >= \
        parse_version(SELECTABLE_BE_VER) and \
            mb_version == MB_NO_ARCHIPELAGO_VER:

        if not options.backend and 'PITHCAT_BACKEND_STORAGE' not in environ:
            stderr.write(
                "Pithos backend storage is missing.\n"
                "Use the PITHCAT_BACKEND_STORAGE environment variable "
                "(recommended) "
                "or the --backend command line option to define it.\n")
            exit(1)

        if options.backend == 'nfs' or \
           environ.get('PITHCAT_BACKEND_STORAGE') == 'nfs':

            if not options.data and 'PITHCAT_DATA' not in environ:
                stderr.write(
                    "Pithos data directory path is missing.\n"
                    "Use the PITHCAT_DATA environment variable "
                    "(recommended) "
                    "or the --data command line option to define it.\n")
                exit(1)

            data_path = environ['PITHCAT_DATA'] if not options.data else \
                options.data
    elif parse_version(pithos_backend_version) < \
            parse_version(SELECTABLE_BE_VER):
        if not options.data and 'PITHCAT_DATA' not in environ:
            stderr.write(
                "Pithos data directory path is missing.\n"
                "Use the PITHCAT_DATA environment variable "
                "(recommended) "
                "or the --data command line option to define it.\n")
            exit(1)
        data_path = environ['PITHCAT_DATA'] if not options.data else \
            options.data

    if options.db is None and 'PITHCAT_DB' not in environ and \
            type(url) is LocationURL:
        stderr.write(
            "Pithos database URI is missing.\n"
            "Use the PITHCAT_DB environment variable (recommended) "
            "or the --db command line option to define it.\n")
        exit(1)

    if type(url) is HashmapURL:
        db_uri = None
    else:
        db_uri = environ['PITHCAT_DB'] if not options.db else options.db

    if parse_version(pithos_backend_version) >= \
       parse_version(SELECTABLE_BE_VER) and \
            mb_version == MB_NO_ARCHIPELAGO_VER:

        block_params = {'mappool': None, 'blockpool': None}
        rados_ceph_conf = None

        backend_storage = environ['PITHCAT_BACKEND_STORAGE'] if not \
            options.backend else options.backend

        if backend_storage == 'rados' and options.rconf is None and \
           'PITHCAT_RADOS_CEPH_CONF' not in environ:
            stderr.write(
                "RADOS storage backend is selected but "
                "RADOS conf file is missing.\n"
                "Use the PITHCAT_RADOS_CEPH_CONF environment variable or the "
                "--rados-conf command line option to define it.\n")
            exit(1)

        if backend_storage == 'rados':
            rados_ceph_conf = environ['PITHCAT_RADOS_CEPH_CONF'] if not \
                options.rconf else options.rconf

            if options.rmaps is None and 'PITHCAT_RADOS_POOL_MAPS' not in \
               environ:
                stderr.write(
                    "RADOS storage backend is selected but "
                    "RADOS pool for Pithos maps is missing.\n"
                    "Use the PITHCAT_RADOS_POOL_MAPS environment variable or "
                    "the --rados-maps command line option to define it.\n")
                exit(1)

            rados_maps = environ['PITHCAT_RADOS_POOL_MAPS'] if not \
                options.rmaps else options.rmaps

            if options.rblocks is None and 'PITHCAT_RADOS_POOL_BLOCKS' not in \
               environ:
                stderr.write(
                    "RADOS storage backend is selected but "
                    "RADOS pool for Pithos blocks is missing.\n"
                    "Use the PITHCAT_RADOS_POOL_BLOCKS environment variable "
                    "or the --rados-blocks command line option to define it.\n"
                )
                exit(1)

            rados_blocks = environ['PITHCAT_RADOS_POOL_BLOCKS'] if not \
                options.rblocks else options.rblocks

            block_params['blockpool'] = rados_blocks
            block_params['mappool'] = rados_maps

        backend_kwargs = {
            "block_path": data_path,
            "block_params": block_params,
            "backend_storage": backend_storage,
            "rados_ceph_conf": rados_ceph_conf
        }
    elif mb_version >= MB_ARCHIPELAGO_VER:

        if not options.archipconf and 'PITHCAT_ARCHIPELAGO_CONF' not \
                in environ:
            stderr.write(
                "Archipelago configuration file is missing.\n"
                "Use the PITHCAT_ARCHIPELAGO_CONF environment variable "
                "(recommended) "
                "or the --archipelago-conf command line option to define it.\n"
            )
            exit(1)

        archipelago_conf_file = environ['PITHCAT_ARCHIPELAGO_CONF'] if not \
            options.archipconf else options.archipconf

        backend_kwargs = {"archipelago_conf_file": archipelago_conf_file}
    else:
        backend_kwargs = {"block_path": data_path}

    if type(url) is LocationURL:
        # Used only for 'pithos://' URLs
        backend_kwargs["db_connection"] = db_uri

    # Initialize Pithos Backend
    backend = ModularBackend(**backend_kwargs)

    try:
        if options.size:
            print_size(backend, url)
        else:
            print_data(backend, url)
    finally:
        if mb_version >= MB_ARCHIPELAGO_VER:
            if backend.ioctx_pool:
                backend.ioctx_pool._shutdown_pool()
        else:
            pass

if __name__ == '__main__':
    main()

# vim: set sta sts=4 shiftwidth=4 sw=4 et ai :
