#!/bin/bash

# Copyright (C) 2012 GRNET S.A.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

. common.sh


if [ -z "$OSP_IMG_ID" ]; then
    log_error "Missing OS API Parameter: OSP_IMG_ID"
    exit 1
fi
if [ -z "$OSP_IMG_FORMAT" ]; then
    log_error "Missing OS API Parameter: OSP_IMG_FORMAT"
    exit 1
fi
if [ -z "$OSP_IMG_PASSWD" ]; then
    log_error "Missing OS API Parameter: OSP_IMG_PASSWD"
    exit 1
fi

IMG_ID=$OSP_IMG_ID
IMG_FORMAT=$OSP_IMG_FORMAT
IMG_PASSWD=$OSP_IMG_PASSWD
if [ -n "$OSP_IMG_PROPERTIES" ]; then
    IMG_PROPERTIES="$OSP_IMG_PROPERTIES"
fi
if [ -n "$OSP_IMG_PERSONALITY" ]; then
    IMG_PERSONALITY="$OSP_IMG_PERSONALITY"
fi


case $IMG_FORMAT in
    extdump|ntfsdump)
        ;;
    diskdump)
        if [ -z "$IMG_PROPERTIES" ]; then
            log_error "\`img_properties' parameter must be present when using \`diskdump' format."
            exit 1
        fi
        ;;
    *)
        log_error "Unknown Image format: \`$IMAGE_TYPE'"
        exit 1
        ;;
esac

exit 0
