#!/bin/bash

dir=$(dirname "$0")
. "$dir"/vif-common.sh

ip link set "$vif" arp off
ip link set "$vif" allmulticast off
ip link set "$vif" dynamic off
ip link set "$vif" multicast off

echo 0 > /proc/sys/net/ipv6/conf/$vif/autoconf
echo 1 > /proc/sys/net/ipv6/conf/$vif/disable_ipv6

ip link set $vif up

success

